### ISSUE TITLE
Feature Request: Script to detect enironment

### ISSUE THREAD

**Issue by mdlewisfb** [Telecominfraproject/OpenCellular#171]
### *Product:* (OC-SDR, OC-LTE, OC-LTE, OC-Power, others)
   N/A
### *Component:* (PSU, GBC, BBU, FEM, LED, ME)
   N/A
### *Category:* (Hardware, Software/stack, Firmware/bootloader, Documentation)
   Software/stack

**Describe the solution you'd like**
There are certain things that will be useful to know about the environment on bug reports. We should have a script in the repo that can be run to collect all that info and output it in an easy to copy and paste format, and then update the Bug Report template to have a section for this info.
First suggestion for what is should include:
- gcc version (for Unit Tests or Middleware)
- gcc-arm-none-eabi version and/or TI CCS version (for Firmware)
- TI RTOS release number
- Operating System
- Github commit hash

**Is your feature request related to a problem? Please describe.**

**Comment by jspectacular** [comment]
Closed with merge of #191
