### ISSUE TITLE
CCS build is broken

### ISSUE THREAD

**Issue by JoshuaJeyaraj** [Telecominfraproject/OpenCellular#176]
### *Product:* (OC-SDR, OC-LTE, OC-LTE, OC-Power, others)
      OCWare

### *Category:* (Hardware, Software/stack, Firmware/bootloader, Documentation)
Software/stack
   
**Describe the issue found**
Build in the TI Code Composer Studio project does not work.
This seems to be because oc_connect1.lds is chosen as the linker config file instead of oc_connect1.cmd

**Please provide all necessary steps to reproduce the issue**
Open TI CCS and try to build the project.

**Comment by mdlewisfb** [comment]
This can be closed now as it was fixed in #179, right?
