### ISSUE TITLE
Test LED module connected to BB

### ISSUE THREAD

**Issue by mayuri2016** [Telecominfraproject/OpenCellular#194]
### *Product:* (OC-SDR, OC-LTE, OC-LTE, OC-Power, All, N/A, others)
   OC-LTE
### *Component:* (PSU, GBC, BBU, FEM, LED, ME)
 BBU
### *Revision:* (A, B, C ...)
Rev C
### *Category: (schematic, layout, BoM, gerber, compliance, testing, documentation, etc.)
Testing
### *Clearly explain the issue in detail, with snippets of schematic (or ref to the exact page), layout, etc, as needed*
Do HW modification to BB to add the LED module to I2C bus 1 and test from u-boot. Verify the device tree and test it in Linux.

**Comment by arulbose** [comment]
The LED board was connected to I2C bus 1 of BB. Below commands were tested from u-boot to verify the ON/OFF LED board and found to be working.
i2c mw 0x3E 0xE.1 0x0;i2c mw 0x3E 0xF.1 0x0;i2c mw 0x3E 0x10.1 0x0;i2c mw 0x3E 0x11.1 0x0
i2c mw 0x3F 0xE.1 0x0;i2c mw 0x3F 0xF.1 0x0;i2c mw 0x3F 0x10.1 0x0;i2c mw 0x3F 0x11.1 0x0

Verified the device tree file for the presence of LED board information on I2C1. Booted to Linux and found the LEDs responding with RED color.
