### ISSUE TITLE
UT framework for OCMP wrapper for debugI2c

### ISSUE THREAD

**Issue by JoshuaJeyaraj** [Telecominfraproject/OpenCellular#79]
### *Product:* (OC-SDR, OC-LTE, OC-LTE, OC-Power, others)
Unit test

### *Component:* (PSU, GBC, BBU, FEM, LED, ME)
  GBC
   
### *Category:* (Hardware, Software/stack, Firmware/bootloader, Documentation)
Software/stack
   
**Describe the solution you'd like**
Expand the current UT framework by adding the ocmp_wrapper layer for debugi2c src/Devices/ocmp_wrappers/ocmp_debugi2c.c

Approach :
The functions in these files are static .
There will be a fxntable with a list of function pointers . We will use these function pointers to call the functions . For I2C register and GPIO access , the existing fake_i2c and fake_gpio infrastructure will be used . Validation will be done based on the return values and output variables.

Test Criteria :
The Unity framework should be successful for all the planned testcases .

**Comment by swateeshrivastava** [comment]
Code is merged into master.
