### ISSUE TITLE
Bug: Issue in reading remote temperature using ADT7481

### ISSUE THREAD

**Issue by JoshuaJeyaraj** [Telecominfraproject/OpenCellular#92]
### *Product:* (OC-SDR, OC-LTE, OC-LTE, OC-Power, others)
      OC-SDR

### *Category:* (Hardware, Software/stack, Firmware/bootloader, Documentation)
   Software/stack

**Describe the issue found**
Issue was found during unit testing 
There seems to be an issue in the way

1) remote1 temperature offset register is modified
2) remote2 temperature offset register is read

Approach :

As per the current code , we are reading ADT7481_REG_R_REMOTE2_OFFSET_L(0x35) twice.
We are reading only the LOW byte value twice , HIGH byte is not read . The second read should we replaced to read ADT7481_REG_R_REMOTE2_OFFSET_H(0x34).

Similarly the write for remote1 temperature offset register needs to be appropriately changed

Test Criteria :
Verify if the read/write is working as expected .

**Comment by swateeshrivastava** [comment]
Code is merged into master.
